### ISSUE TITLE
Is training QMIX on Google Football with the local observations?

### ISSUE THREAD

**Issue by GoingMyWay** [Fabien-Couthouis/XAI-in-RL#1]
Dear Fabien,

Is training QMIX on Google Football with the local observations?  At each step, will each agent get its own individual reward or the global reward?

**Comment by Fabien-Couthouis** [comment]
Hi Alexander,

Thanks for your interest!
As far as I know, Google Research Football only provides global observations, so we tried to train Qmix agents with the global observation (we took the floats vector observation). Reward obtained by each agent corresponds to the global reward obtained by the team.
More details about rewards and observation can be found in [Google Research Football paper](https://arxiv.org/pdf/1907.11180.pdf).

However, the agents we trained were not very satisfactory for the multiagent 5 vs 5 scenario in Google Research Football, so if you manage to get some good model with a bit of teamplay, do not hesitate to share it, this would be very valuable for us :) .

**Comment by GoingMyWay** [comment]
> Hi Alexander,
> 
> Thanks for your interest!
> As far as I know, Google Research Football only provides global observations, so we tried to train Qmix agents with the global observation (we took the floats vector observation). Reward obtained by each agent corresponds to the global reward obtained by the team.
> More details about rewards and observation can be found in [Google Research Football paper](https://arxiv.org/pdf/1907.11180.pdf).
> 
> However, the agents we trained were not very satisfactory for the multiagent 5 vs 5 scenario in Google Research Football, so if you manage to get some good model with a bit of teamplay, do not hesitate to share it, this would be very valuable for us :) .

Thank you.
